### PR TITLE
README copyediting; .gitignore

### PR DESCRIPTION
**Pull request by cxw42**
- Formatting and minor copyediting in README.md
- Indent with spaces in README.md to avoid the problem of 4 vs. 8
  in browser rendering
- Add a basic .gitignore

Thank you for considering this PR!

### CODE REVIEW

**Comment by zenaan** [comment]
In general I prefer all code, even say the psuedo code in README.md, to be formatted with tabs. There's a link at the bottom of README.md to a browser plugin ("stylish") which can format actual tabs at any preferred indent, on all websites.

The principle is that tabs really ought be a user configurable thing, everywhere. In the GitHub world I am hoping folks are not too averse to installing a browser plugin in this case - it has obvious benefits beyond any single project and means code can stay tabbed, and users can maintain their preferred indent_size - this is a big part of what attracted me to EditorConfig in the first instance, and has caused me to change all my code (shell and Java) to be TAB and not space indented.

What do you think?

**Comment by zenaan** [comment]
PS: thank you for the rest of your tidy ups and fixes. I'll wait for your feedback on the above before merging.

**Comment by zenaan** [comment]
Quick question: do you use a `~/.config/git/ignore` (or similar) "local global" vim config?

I do, and sort of came to the conclusion that per-repository .gitignores make most sense for files the project tools (or makefiles) themselves produce, rather than standard editor swap files - which, if you use a particular editor, you would use it across many projects, and the .ignore rule should apply to all of them...

**Comment by cxw42** [comment]
- I'll change the spaces back to tabs - it's your repo :) .  I use all spaces, myself, except for Makefiles.  I have seen a great many projects that used tab+space for alignment, thereby forcing the choice of tab size.

Please do understand most of the EditorConfig code I've seen uses spaces, so this may come up again later in an EditorConfig context 

- I do not have a global exclude for swap files - interesting idea!  If not .gitignore, I usually use .git/info/exclude.  I actually don't have any global ignores, since I have been bitten in the past by ignores from one repo negatively affecting another repo.  (I can't remember the details, but I remember that it happened.)

**Comment by zenaan** [comment]
> I have seen a great many projects that used tab+space for alignment, thereby forcing the choice of tab size.

OMGod, that's an abomination and a half! :/ :\

**Comment by zenaan** [comment]
Merged - kept original pseudo code tabs.
Thanks for the fixes :)

**Pull request merged**
